name: Analyzer

on:
  workflow_dispatch:

jobs:
  # =============================================================================
  # JOB: ANALYZER
  # =============================================================================
  analyzer:
    runs-on: ubuntu-latest
    name: OSO ORT
    steps:
      - uses: actions/checkout@v3
      - name: Run OSO ORT Analyzer and Submit to Scanner API
        id: analyzer
        uses: porscheofficial/.github/workflows/ort-analyze@main
        with:
          ort-aws-access-key-id: ${{ secrets.ANALYZER_AWS_ACCESS_KEY_ID }}
          ort-aws-secret-access-key: ${{ secrets.ANALYZER_AWS_ACCESS_KEY }}
          container-repository: ${{ secrets.ANALYZER_DOCKER_IMAGE }}
          container-registry: ${{ secrets.ANALYZER_DOCKER_REGISTRY }}
